version: "3.8"
services:
  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data --certs-dir /certs
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - ./minio_data:/data
    networks:
      - minio_network

networks:
  minio_network: